#!/bin/bash

SWAPFILE=/home/swapfile.swp
SANDBOX=/mnt/bin/sandbox
INTERPRETOR=/mnt/bin/interpretor
SHARE=/home/build

# Ensure 1GB swap, our 256MB is not enough to link stuff
#
if [ ! -f ${SWAPFILE} ]; then
  dd if=/dev/zero of=${SWAPFILE} bs=1024 count=1048576
  mkswap ${SWAPFILE}
fi

swapon ${SWAPFILE}

# Mount the share
if [ ! -d ${SHARE} ]; then
  mkdir ${SHARE}
fi
mount -t 9p share ${SHARE}

if [ -z "$INTERACTIVE" ]; then
  # Run the interpretor
  echo "Running the interpretor"
  export SHARE
  ${INTERPRETOR}
else
  # Run an interactive shell
  echo "Running interactive shell"
  ${SHELL} -i
fi
